import images from "../../assets/images/images"

const playersData = [
  {
    id: "1",
    first_name: "David",
    last_name: "Thuo",
    image: images.player1,
    category: "Goalkeeper",
  },
  {
    id: "2",
    first_name: "Ian",
    last_name: "Kosgei",
    image: images.player2,
    category: "Goalkeeper",
  },
  {
    id: "3",
    first_name: "Filemon",
    last_name: "Kiplagat",
    image: images.player3,
    category: "Midfielder",
  },
  {
    id: "4",
    first_name: "Isaac",
    last_name: "Mungoya",
    image: images.player4,
    category: "Defender",
  },
  {
    id: "5",
    first_name: "Daniel",
    last_name: "Waicere",
    image: images.player5,
    category: "Forward",
  },
  {
    id: "6",
    first_name: "Paul",
    last_name: "Mutai",
    image: images.player6,
    category: "Midfielder",
  },
  {
    id: "7",
    first_name: "Dancan",
    last_name: "Kiago",
    image: images.player7,
    category: "Defender",
  },
  {
    id: "8",
    first_name: "Charles",
    last_name: "Waweru",
    image: images.player8,
    category: "Midfielder",
  },
  {
    id: "9",
    first_name: "David",
    last_name: "Lopeyok",
    image: images.player9,
    category: "Defender",
  },
  {
    id: "10",
    first_name: "Francis",
    last_name: "Lubisia",
    image: images.player10,
    category: "Defender",
  },
  {
    id: "11",
    first_name: "Lennox",
    last_name: "Wafula",
    image: images.player11,
    category: "Defender",
  },
  {
    id: "12",
    first_name: "Daniel",
    last_name: "Kiptum",
    image: images.player12,
    category: "Defender",
  },
  {
    id: "13",
    first_name: "Bernard",
    last_name: "Wanjala",
    image: images.player13,
    category: "Midfielder",
  },
  {
    id: "14",
    first_name: "Peter",
    last_name: "Wamalwa",
    image: images.player14,
    category: "Defender",
  },
  {
    id: "15",
    first_name: "Derick",
    last_name: "Ekai",
    image: images.player15,
    category: "Defender",
  },
  {
    id: "16",
    first_name: "Moses",
    last_name: "Kariuki",
    image: images.player16,
    category: "Midfielder",
  },
  {
    id: "17",
    first_name: "Keith",
    last_name: "Kamuhia",
    image: images.player17,
    category: "Forward",
  },
  {
    id: "18",
    first_name: "Kelas",
    last_name: "Wekesa",
    image: images.player18,
    category: "Forward",
  },
];

export default playersData;
